# Generated by Django 4.2 on 2024-07-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('D', 'Drama'), ('A', 'Accion'), ('C', 'Comedia'), ('T', 'Terror')], max_length=30)),
                ('director_name', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
