# Generated by Django 4.2 on 2024-07-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('T', 'Terror'), ('A', 'Accion'), ('C', 'Comedia'), ('D', 'Drama')], max_length=30),
        ),
    ]
