# Generated by Django 4.2 on 2024-07-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_synopsis_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('A', 'Accion'), ('D', 'Drama'), ('C', 'Comedia'), ('T', 'Terror')], max_length=30),
        ),
    ]
